<?php
function adk_theme_stup(){
    
    // Ajout la prise en charge du format de la publication
    add_theme_support( 'post-formats', array( 'image','video','gallery','audio', 'aside') );
    //Ajout de la personnalisation de l'entête
	add_theme_support( 'custom-header' ); 
    remove_filter ('the_content', 'wpautop');
    // Ajout de la personnalisation de l'arrière plan
	add_theme_support( 'custom-background' );
    // Ajout la prise en charge des images mises en avant
    add_theme_support( 'post-thumbnails' );

    // Ajout automatiquement le titre du site dans l'en-tête du site
	add_theme_support( 'title-tag' );
	
	add_theme_support( 'customize-selective-refresh-widgets' );

    add_theme_support( 'html5', array( 'search-form', 'comment-form', 'comment-list', 'gallery', 'caption', 'style', 'script' ) );

}
add_action( 'after_setup_theme', 'adk_theme_stup' );


// Ajout le menu de navigation
function adk_nav_menu() {
    register_nav_menu('primary',__( 'Header Menu' ));
  }
  add_action( 'init', 'adk_nav_menu' );

function adk_theme_scripts_styles() {
    $protocol = is_ssl() ? 'https' : 'http';
    //Style
    wp_enqueue_style( 'bootstrap', get_template_directory_uri().'/assets/css/bootstrap.min.css');
    wp_enqueue_style( 'font-awesome', get_template_directory_uri().'/assets/css/font-awesome.min.css');
    wp_enqueue_style( 'flaticon', get_template_directory_uri().'/assets/css/flaticon.css');
    wp_enqueue_style( 'nice-select', get_template_directory_uri().'/assets/css/nice-select.css');
    wp_enqueue_style( 'animate', get_template_directory_uri().'/assets/css/animate.min.css');
    wp_enqueue_style( 'magnific-popup', get_template_directory_uri().'/assets/css/magnific-popup.css');
    wp_enqueue_style( 'slick', get_template_directory_uri().'/assets/css/slick.css');
    wp_enqueue_style( 'default', get_template_directory_uri().'/assets/css/default.css');
	wp_enqueue_style( 'main', get_template_directory_uri().'/assets/css/main.css');
	wp_enqueue_style("style", get_stylesheet_uri(), NULL, microtime());
    //Javascript
    wp_enqueue_script("modernizr-3.6.0", get_template_directory_uri()."/assets/js/vendor/modernizr-3.6.0.min.js",array(),false,true);
    wp_enqueue_script("jquery-3.5.0", get_template_directory_uri()."/assets/js/vendor/jquery-3.5.0.js",array(),false,true);
    wp_enqueue_script("bootstrap", get_template_directory_uri()."/assets/js/bootstrap.min.js",array(),false,true);
    wp_enqueue_script("popper", get_template_directory_uri()."/assets/js/popper.min.js",array(),false,true);
    wp_enqueue_script("slick", get_template_directory_uri()."/assets/js/slick.min.js",array(),false,true);
    wp_enqueue_script("jquery.counterup", get_template_directory_uri()."/assets/js/jquery.counterup.min.js",array(),false,true);
    wp_enqueue_script("jquery.waypoints", get_template_directory_uri()."/assets/js/jquery.waypoints.min.js",array(),false,true);
    wp_enqueue_script("wow", get_template_directory_uri()."/assets/js/wow.js",array(),false,true);
    wp_enqueue_script("jquery.nice-select", get_template_directory_uri()."/assets/js/jquery.nice-select.min.js",array(),false,true);
    wp_enqueue_script("jquery.magnific-popup", get_template_directory_uri()."/assets/js/jquery.magnific-popup.min.js",array(),false,true);
    wp_enqueue_script("main", get_template_directory_uri()."/assets/js/main.js",array(),false,true);

}  
add_action( 'wp_enqueue_scripts', 'adk_theme_scripts_styles' );

function adk_custom_logo_setup() {
    $defaults = array(
    'height'      => 100,
    'width'       => 400,
    'flex-height' => true,
    'flex-width'  => true,
    'header-text' => array( 'site-title', 'site-description' ),
    );
    add_theme_support( 'custom-logo', $defaults );
   }
   add_action( 'after_setup_theme', 'adk_custom_logo_setup' );

  
 // Générer le  breadcrumbs
 
function get_breadcrumb() {
    echo '<li class="breadcrumb-item"><a href="'.home_url().'" rel="nofollow">Accueil</a></li>';
    if (is_category() || is_single()) {
       the_category();
         /*echo '<li class="breadcrumb-item">'.the_category().'</li>';*/
            if (is_single()) {
                the_title('<li class="breadcrumb-item active" aria-current="page">', '</li>');
            }
    } elseif (is_page()) {
        echo the_title('<li class="breadcrumb-item active" aria-current="page">', '</li>');
    } elseif (is_search()) {
        echo "&nbsp;&nbsp;&#187;&nbsp;&nbsp;Search Results for... ";
        echo '"<em>';
        echo the_search_query();
        echo '</em>"';
    }
}

/**
 * Generated by the WordPress Option Page generator
 * at http://jeremyhixon.com/wp-tools/option-page/
 */

class ParamtreADKTheme {
	private $paramtre_adk_theme__options;

	public function __construct() {
		add_action( 'admin_menu', array( $this, 'paramtre_adk_theme__add_plugin_page' ) );
		add_action( 'admin_init', array( $this, 'paramtre_adk_theme__page_init' ) );
	}

	public function paramtre_adk_theme__add_plugin_page() {
		add_theme_page(
			'Paramètre ADK Theme ', // page_title
			'Paramètre ADK Theme ', // menu_title
			'manage_options', // capability
			'paramtre-adk-theme', // menu_slug
			array( $this, 'paramtre_adk_theme__create_admin_page' ) // function
		);
	}

	public function paramtre_adk_theme__create_admin_page() {
		$this->paramtre_adk_theme__options = get_option( 'paramtre_adk_theme__option_name' ); ?>

		<div class="wrap">
			<h2>Paramètre ADK Theme </h2>
			<p></p>
			<?php settings_errors(); ?>

			<form method="post" action="options.php">
				<?php
					settings_fields( 'paramtre_adk_theme__option_group' );
					do_settings_sections( 'paramtre-adk-theme-admin' );
					submit_button();
				?>
			</form>
		</div>
	<?php }

	public function paramtre_adk_theme__page_init() {
		register_setting(
			'paramtre_adk_theme__option_group', // option_group
			'paramtre_adk_theme__option_name', // option_name
			array( $this, 'paramtre_adk_theme__sanitize' ) // sanitize_callback
		);

		add_settings_section(
			'paramtre_adk_theme__setting_section', // id
			'Settings', // title
			array( $this, 'paramtre_adk_theme__section_info' ), // callback
			'paramtre-adk-theme-admin' // page
		);

		add_settings_field(
			'e_mail_0', // id
			'E-mail', // title
			array( $this, 'e_mail_0_callback' ), // callback
			'paramtre-adk-theme-admin', // page
			'paramtre_adk_theme__setting_section' // section
		);

		add_settings_field(
			'tlphone_1', // id
			'Téléphone', // title
			array( $this, 'tlphone_1_callback' ), // callback
			'paramtre-adk-theme-admin', // page
			'paramtre_adk_theme__setting_section' // section
		);

		add_settings_field(
			'adresse_2', // id
			'Adresse', // title
			array( $this, 'adresse_2_callback' ), // callback
			'paramtre-adk-theme-admin', // page
			'paramtre_adk_theme__setting_section' // section
		);

		add_settings_field(
			'facebook_3', // id
			'Facebook', // title
			array( $this, 'facebook_3_callback' ), // callback
			'paramtre-adk-theme-admin', // page
			'paramtre_adk_theme__setting_section' // section
		);

		add_settings_field(
			'twitter_4', // id
			'Twitter', // title
			array( $this, 'twitter_4_callback' ), // callback
			'paramtre-adk-theme-admin', // page
			'paramtre_adk_theme__setting_section' // section
		);

		add_settings_field(
			'linkedin_5', // id
			'Linkedin', // title
			array( $this, 'linkedin_5_callback' ), // callback
			'paramtre-adk-theme-admin', // page
			'paramtre_adk_theme__setting_section' // section
		);

		add_settings_field(
			'instagram_6', // id
			'Instagram', // title
			array( $this, 'instagram_6_callback' ), // callback
			'paramtre-adk-theme-admin', // page
			'paramtre_adk_theme__setting_section' // section
		);

		add_settings_field(
			'rss_7', // id
			'RSS', // title
			array( $this, 'rss_7_callback' ), // callback
			'paramtre-adk-theme-admin', // page
			'paramtre_adk_theme__setting_section' // section
		);

		add_settings_field(
			'copyright_8', // id
			'copyright', // title
			array( $this, 'copyright_8_callback' ), // callback
			'paramtre-adk-theme-admin', // page
			'paramtre_adk_theme__setting_section' // section
		);
	}

	public function paramtre_adk_theme__sanitize($input) {
		$sanitary_values = array();
		if ( isset( $input['e_mail_0'] ) ) {
			$sanitary_values['e_mail_0'] = sanitize_text_field( $input['e_mail_0'] );
		}

		if ( isset( $input['tlphone_1'] ) ) {
			$sanitary_values['tlphone_1'] = sanitize_text_field( $input['tlphone_1'] );
		}

		if ( isset( $input['adresse_2'] ) ) {
			$sanitary_values['adresse_2'] = sanitize_text_field( $input['adresse_2'] );
		}

		if ( isset( $input['facebook_3'] ) ) {
			$sanitary_values['facebook_3'] = sanitize_text_field( $input['facebook_3'] );
		}

		if ( isset( $input['twitter_4'] ) ) {
			$sanitary_values['twitter_4'] = sanitize_text_field( $input['twitter_4'] );
		}

		if ( isset( $input['linkedin_5'] ) ) {
			$sanitary_values['linkedin_5'] = sanitize_text_field( $input['linkedin_5'] );
		}

		if ( isset( $input['instagram_6'] ) ) {
			$sanitary_values['instagram_6'] = sanitize_text_field( $input['instagram_6'] );
		}

		if ( isset( $input['rss_7'] ) ) {
			$sanitary_values['rss_7'] = sanitize_text_field( $input['rss_7'] );
		}

		if ( isset( $input['copyright_8'] ) ) {
			$sanitary_values['copyright_8'] = esc_textarea( $input['copyright_8'] );
		}

		return $sanitary_values;
	}

	public function paramtre_adk_theme__section_info() {
		
	}

	public function e_mail_0_callback() {
		printf(
			'<input class="regular-text" type="text" name="paramtre_adk_theme__option_name[e_mail_0]" id="e_mail_0" value="%s">',
			isset( $this->paramtre_adk_theme__options['e_mail_0'] ) ? esc_attr( $this->paramtre_adk_theme__options['e_mail_0']) : ''
		);
	}

	public function tlphone_1_callback() {
		printf(
			'<input class="regular-text" type="text" name="paramtre_adk_theme__option_name[tlphone_1]" id="tlphone_1" value="%s">',
			isset( $this->paramtre_adk_theme__options['tlphone_1'] ) ? esc_attr( $this->paramtre_adk_theme__options['tlphone_1']) : ''
		);
	}

	public function adresse_2_callback() {
		printf(
			'<input class="regular-text" type="text" name="paramtre_adk_theme__option_name[adresse_2]" id="adresse_2" value="%s">',
			isset( $this->paramtre_adk_theme__options['adresse_2'] ) ? esc_attr( $this->paramtre_adk_theme__options['adresse_2']) : ''
		);
	}

	public function facebook_3_callback() {
		printf(
			'<input class="regular-text" type="text" name="paramtre_adk_theme__option_name[facebook_3]" id="facebook_3" value="%s">',
			isset( $this->paramtre_adk_theme__options['facebook_3'] ) ? esc_attr( $this->paramtre_adk_theme__options['facebook_3']) : ''
		);
	}

	public function twitter_4_callback() {
		printf(
			'<input class="regular-text" type="text" name="paramtre_adk_theme__option_name[twitter_4]" id="twitter_4" value="%s">',
			isset( $this->paramtre_adk_theme__options['twitter_4'] ) ? esc_attr( $this->paramtre_adk_theme__options['twitter_4']) : ''
		);
	}

	public function linkedin_5_callback() {
		printf(
			'<input class="regular-text" type="text" name="paramtre_adk_theme__option_name[linkedin_5]" id="linkedin_5" value="%s">',
			isset( $this->paramtre_adk_theme__options['linkedin_5'] ) ? esc_attr( $this->paramtre_adk_theme__options['linkedin_5']) : ''
		);
	}

	public function instagram_6_callback() {
		printf(
			'<input class="regular-text" type="text" name="paramtre_adk_theme__option_name[instagram_6]" id="instagram_6" value="%s">',
			isset( $this->paramtre_adk_theme__options['instagram_6'] ) ? esc_attr( $this->paramtre_adk_theme__options['instagram_6']) : ''
		);
	}

	public function rss_7_callback() {
		printf(
			'<input class="regular-text" type="text" name="paramtre_adk_theme__option_name[rss_7]" id="rss_7" value="%s">',
			isset( $this->paramtre_adk_theme__options['rss_7'] ) ? esc_attr( $this->paramtre_adk_theme__options['rss_7']) : ''
		);
	}

	public function copyright_8_callback() {
		printf(
			'<textarea class="large-text" rows="5" name="paramtre_adk_theme__option_name[copyright_8]" id="copyright_8">%s</textarea>',
			isset( $this->paramtre_adk_theme__options['copyright_8'] ) ? esc_attr( $this->paramtre_adk_theme__options['copyright_8']) : ''
		);
	}

}
if ( is_admin() )
	$paramtre_adk_theme_ = new ParamtreADKTheme();

/* 
 * Retrieve this value with:
 * $paramtre_adk_theme__options = get_option( 'paramtre_adk_theme__option_name' ); // Array of All Options
 * $e_mail_0 = $paramtre_adk_theme__options['e_mail_0']; // E-mail
 * $tlphone_1 = $paramtre_adk_theme__options['tlphone_1']; // Téléphone
 * $adresse_2 = $paramtre_adk_theme__options['adresse_2']; // Adresse
 * $facebook_3 = $paramtre_adk_theme__options['facebook_3']; // Facebook
 * $twitter_4 = $paramtre_adk_theme__options['twitter_4']; // Twitter
 * $linkedin_5 = $paramtre_adk_theme__options['linkedin_5']; // Linkedin
 * $instagram_6 = $paramtre_adk_theme__options['instagram_6']; // Instagram
 * $rss_7 = $paramtre_adk_theme__options['rss_7']; // RSS
 * $copyright_8 = $paramtre_adk_theme__options['copyright_8']; // copyright
 */
// Ajout de widgets au footer
function adktheme_widgets_init() {
 
    // Zone de widget du premier pied de page, située dans le pied de page. Vide par défaut.
    register_sidebar( array(
        'name' => __( 'Zone de widget du premier pied de page'),
        'id' => 'first-footer-widget-area',
        'description' => __( 'La première zone de widget de pied de page'),
        'before_widget' => '<div id="%1$s" class="widget-container %2$s">',
        'after_widget' => '</div>',
        'before_title' => '<h3 class="title">',
        'after_title' => '</h3>',
    ) );
 
    // Zone de widget du deuxième pied de page, située dans le pied de page. Vide par défaut.
    register_sidebar( array(
        'name' => __( 'Zone de widget du deuxième pied de page'),
        'id' => 'second-footer-widget-area',
        'description' => __( 'La zone de widget du deuxième pied de page'),
        'before_widget' => '<div id="%1$s" class="widget-container %2$s">',
        'after_widget' => '</div>',
        'before_title' => '<h3 class="title">',
        'after_title' => '</h3>',
    ) );
 
    // Zone du widget du troisième pied de page, située dans le pied de page. Vide par défaut.
    register_sidebar( array(
        'name' => __( 'Zone du widget du troisième pied de page'),
        'id' => 'third-footer-widget-area',
        'description' => __( 'La zone du widget du troisième pied de page'),
        'before_widget' => '<div id="%1$s" class="widget-container %2$s">',
        'after_widget' => '</div>',
        'before_title' => '<h3 class="title">',
        'after_title' => '</h3>',
    ) );
 
    // Zone du widget du quatrième pied de page, située dans le pied de page. Vide par défaut.
    register_sidebar( array(
        'name' => __( 'Zone du widget du quatrième pied de page'),
        'id' => 'fourth-footer-widget-area',
        'description' => __( 'La zone de widget quatrième pied de page'),
        'before_widget' => '<div id="%1$s" class="widget-container %2$s">',
        'after_widget' => '</div>',
        'before_title' => '<h3 class="title">',
        'after_title' => '</h3>',
	) );
	

	// Sidebar article singulier

	register_sidebar(array(
		'name' => __( 'Zone Article Sidebar' ),
		'id' => 'post-sidebar',
		'description' => __( 'Sidebar page article' ),
		'before_widget' => '<div id="%1$s" class="widget-container %2$s">',
        'after_widget' => '</div>',
        'before_title' => '<h3 class="hidd_widget__title">',
        'after_title' => '</h3>',
	));
         
}
 
// Register sidebars by running tutsplus_widgets_init() on the widgets_init hook.
add_action( 'widgets_init', 'adktheme_widgets_init' );

// Ajout de la pagination à la liste de blog
function adktheme_blog_pagination($pages = '', $range = 2) 
{  
	$showitems = ($range * 2) + 1;  
	global $paged;
	if(empty($paged)) $paged = 1;
	if($pages == '')
	{
		global $wp_query; 
		$pages = $wp_query->max_num_pages;
	
		if(!$pages)
			$pages = 1;		 
	}   
	
	if(1 != $pages)
	{
	    echo '<nav aria-label="Page navigation" role="navigation">';
        echo '<span class="sr-only">Page navigation</span>';
        echo '<ul class="pagination justify-content-center ft-wpbs">';
		
        echo '<li class="page-item disabled hidden-md-down d-none d-lg-block"><span class="page-link">Page '.$paged.' sur '.$pages.'</span></li>';
	
	 	if($paged > 2 && $paged > $range+1 && $showitems < $pages) 
			echo '<li class="page-item"><a class="page-link" href="'.get_pagenum_link(1).'" aria-label="First Page">&laquo;<span class="hidden-sm-down d-none d-md-block"> First</span></a></li>';
	
	 	if($paged > 1 && $showitems < $pages) 
			echo '<li class="page-item"><a class="page-link" href="'.get_pagenum_link($paged - 1).'" aria-label="Previous Page">&lsaquo;<span class="hidden-sm-down d-none d-md-block"> Previous</span></a></li>';
	
		for ($i=1; $i <= $pages; $i++)
		{
		    if (1 != $pages &&( !($i >= $paged+$range+1 || $i <= $paged-$range-1) || $pages <= $showitems ))
				echo ($paged == $i)? '<li class="page-item active"><span class="page-link"><span class="sr-only">Current Page </span>'.$i.'</span></li>' : '<li class="page-item"><a class="page-link" href="'.get_pagenum_link($i).'"><span class="sr-only">Page </span>'.$i.'</a></li>';
		}
		
		if ($paged < $pages && $showitems < $pages) 
			echo '<li class="page-item"><a class="page-link" href="'.get_pagenum_link($paged + 1).'" aria-label="Next Page"><span class="hidden-sm-down d-none d-md-block">Next </span>&rsaquo;</a></li>';  
	
	 	if ($paged < $pages-1 &&  $paged+$range-1 < $pages && $showitems < $pages) 
			echo '<li class="page-item"><a class="page-link" href="'.get_pagenum_link($pages).'" aria-label="Last Page"><span class="hidden-sm-down d-none d-md-block">Last </span>&raquo;</a></li>';
	
	 	echo '</ul>';
        echo '</nav>';
        //echo '<div class="pagination-info mb-5 text-center">[ <span class="text-muted">Page</span> '.$paged.' <span class="text-muted">of</span> '.$pages.' ]</div>';	 	
	}
}


// Customisation du widget de recherche
 function adktheme_search_form( $form ) {
	$form = '<div class="sidebar__single sidebar__search">
		<form method="get" action="'.esc_url(home_url('/')).'" class="sidebar__search-form">
			<input type="text" name="s" placeholder="'.esc_attr__('Recherche...').'" value="'.get_search_query().'">
			<button type="submit"><i class="fa fa-search"></i></button>
		</form>
	</div>';
    return $form;
}
add_filter( 'get_search_form', 'adktheme_search_form' );

 function adktheme_recent_posts(){ 
	echo '<div class="mt-20 mb-20 sidebar__single sidebar__post">';
	echo '<h3 class="sidebar__title">Actualités récentes</h3>';
	echo '<div class="sidebar__post-wrap">';
	 	 $recent_posts = wp_get_recent_posts(array(
			'numberposts' => 3, // Number of recent posts thumbnails to display
			'post_status' => 'publish' // Show only the published posts
    		));
			foreach($recent_posts as $post){
		echo '<div class="sidebar__post__single">
				<div class="sidebar__post-image">
					<div class="inner-block">'.get_the_post_thumbnail($post["ID"], array(80, 80)).'</div>
				</div>
				<div class="sidebar__post-content">
					<h4 class="sidebar__post-title"><a href="'.get_permalink($post["ID"]).'">'.esc_html($post["post_title"]).'</a></h4>
				</div>
			</div>';
			}
	echo '</div>';
	echo '</div>';
}
add_filter( 'widget_posts_args', 'adktheme_recent_posts' );

function adktheme_widget_categories($categories){

		$categories = get_categories( array(
			'orderby' => 'name',
			'order'   => 'ASC',
			'hide_empty' => true
		) );
		echo '<ul class="sidebar__category-list">';
		foreach($categories as $categorie){
			echo '<li class="sidebar__category-list-item"><a href="'.get_category_link($categorie->term_id).'">'.$categorie->name.' ('.$categorie->count.')<i class="fa fa-angle-right"></i></a></li>';
		}
		echo '</ul>';
}
add_filter( 'wp_list_categories', 'adktheme_widget_categories' ); 


function special_nav_class ($classes, $item) {
  if (in_array('current-menu-item', $classes) ){
    $classes[] = 'menu-item-has-children active ';
  }
  return $classes;
}
add_filter('nav_menu_css_class' , 'special_nav_class' , 10 , 2);

function sendSMS($from,$to,$text,$dlrurl="",$token="7wH9MOXwdYBT3Cy21nve4_ioy_VUF4kM"){
    // your access key 
    $text = urlencode($text);
    $url="http://www.wassasms.com/wassasms/api/web/v3/sends?access-token=".$token."&sender="
    .$from."&receiver=".$to."&text=".$text;
    $curl = curl_init();
    trim($url);
    curl_setopt($curl, CURLOPT_URL, $url);
    curl_setopt($curl, CURLOPT_COOKIESESSION, true);
    curl_setopt($curl, CURLOPT_RETURNTRANSFER, true);

    $return = curl_exec($curl);
    $retour = trim($return);

    return $retour;              
}

function adkSms(){

	if( isset($_GET["phone"])) {
		$recever = $_GET["phone"];
		//Envoie en se servant de la fonction sendSMS.
		$from="Adkontact";$to=$recever;$text=urlencode("Bienvenue sur Adkontact SMS la meilleure offre SMS sur le marché");
		$return = sendSMS($from, $to, $text);
	 }
	 ob_start();
	?>
	<div class="write-massage-content">
		<div class="write-massage-input">
			<form action = "<?php $_PHP_SELF ?>" method = "GET">
			<div class="row">
				<div class="col-lg-12">
				<div class="input-box mt-10">
					<input type = "text" name = "phone" placeholder="Votre numéro de téléphone" required />
				</div>
				</div>
				<div class="col-lg-12">
				<div class="input-box mt-10 text-center">
					<button class='main-btn main-btn-2'>Tester votre numéro</button>
				</div>
				</div>
			</div>
			</form>
		</div>
	</div>
	<?php
	return ob_get_clean();
}
add_shortcode('adksmsTest', 'adkSms');

?>